-- ========================================
-- EXTENSIONS
-- ========================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ========================================
-- TABLE: certificates
-- ========================================

CREATE TABLE public.certificates (
    id bigint NOT NULL,
    title text NOT NULL,
    image_url text,
    created_at timestamp without time zone DEFAULT now()
);

ALTER TABLE public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);

ALTER TABLE public.certificates
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: comments
-- ========================================

CREATE TABLE public.comments (
    id bigint NOT NULL,
    name text,
    comment text NOT NULL,
    image_url text,
    likes integer DEFAULT 0,
    is_pinned boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    liked_by_admin boolean DEFAULT false,
    project_id bigint,
    parent_id bigint,
    CONSTRAINT comments_project_id_fkey FOREIGN KEY (project_id) REFERENCES "Projects" (id),
    CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES comments (id)
);

ALTER TABLE public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: Projects
-- ========================================

CREATE TABLE public."Projects" (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    live_url text,
    github_url text,
    technologies text[] DEFAULT '{}'::text[],
    key_features text[] DEFAULT '{}'::text[],
    image_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    image_urls jsonb DEFAULT '[]'::jsonb
);

ALTER TABLE public."Projects"
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

-- ========================================
-- TABLE: tech_stack
-- ========================================

CREATE TABLE public.tech_stack (
    id bigint NOT NULL,
    name text NOT NULL,
    logo_url text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.tech_stack
    ADD CONSTRAINT tech_stack_pkey PRIMARY KEY (id);

ALTER TABLE public.tech_stack
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: profiles (for role-based access)
-- ========================================

CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  role text DEFAULT 'user',
  PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own profile"
ON public.profiles
FOR SELECT
USING (auth.uid() = id);

-- ========================================
-- FUNCTION: is_admin (for checking roles)
-- ========================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- FUNCTION & TRIGGER: handle_new_user
-- ========================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ========================================
-- INDEXES
-- ========================================

CREATE INDEX idx_projects_created_at
ON public."Projects"(created_at);

CREATE INDEX idx_comments_created_at
ON public.comments(created_at);

-- ========================================
-- ROW LEVEL SECURITY
-- ========================================

ALTER TABLE public."Projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tech_stack ENABLE ROW LEVEL SECURITY;

-- ========================================
-- POLICIES (OPEN PUBLIC ACCESS)
-- ========================================

CREATE POLICY "Allow public read projects"
ON public."Projects"
FOR SELECT
USING (true);

CREATE POLICY "Allow public insert comments"
ON public.comments
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public read comments"
ON public.comments
FOR SELECT
USING (true);

CREATE POLICY "Allow public read certificates"
ON public.certificates
FOR SELECT
USING (true);

CREATE POLICY "Allow public read tech_stack"
ON public.tech_stack
FOR SELECT
USING (true);

-- ========================================
-- POLICIES (ADMIN ACCESS)
-- ========================================

CREATE POLICY "Allow admin to update comments"
ON public.comments
FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE POLICY "Allow admin to delete comments"
ON public.comments
FOR DELETE
TO authenticated
USING (public.is_admin());

CREATE POLICY "Allow admin to view all profiles"
ON public.profiles
FOR SELECT
TO authenticated
USING (public.is_admin());

CREATE POLICY "Allow admin to update profiles"
ON public.profiles
FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- ========================================
-- UPDATED_AT TRIGGER
-- ========================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_projects_updated_at
BEFORE UPDATE ON public."Projects"
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ========================================
-- TRIGGER: on_auth_user_created
-- ========================================

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();